### ISSUE TITLE
[Feature Request] Key modifier instead of right click to enable mouse wheel tab scrolling?

### ISSUE THREAD

**Issue by LunarBear** [raburton/tabscroller#10]
Hey, amazing addon, I love it, I was using Gesturify just for this before but I'd much rather use this.

Just a simple question / feature request, if it is even doable: would it be possible to assign a key modifier (ctrl, alt, shift or a combination of those) instead of right click to enable scrolling with mouse wheel? I.e. I'd like to be able to scroll tabs with mouse wheel while holding Alt (default is previous/next page that I don't care about) or Shift (default doesn't even do anything). 

Thanks!

**Comment by raburton** [comment]
Yes, possible and already coded, but needed some people to test it a bit - looks like you just volunteered ;-)
https://www.dropbox.com/s/usy2b7jmrhiaczx/tabscroller-v1.0.8.zip?dl=1
Unzip this somewhere to a folder on your pc, go to the Add-ons page in firefox, click the settings icon top right, choose Debug Add-ons, then click Load Temporary Add-on and navigate to the manifest file you extracted from the zip file. Go to the add-on options to choose your keys.

Let me know how you get on...

**Comment by LunarBear** [comment]
Well that was fast! Fantastic! I used an AHK script temporarily to do that but I'd much rather use an addon. Yours works perfectly, and does exactly what I want. Thanks! I'll report to you if I find any bug.

**Comment by raburton** [comment]
Thanks. I'll let you have a play with it for a few days and if you don't
find any problems I'll release it.

**Comment by LunarBear** [comment]
Hey, coming back to tell you that it works great! Tried all the shortcuts just for testing purpose and it works well. 

The only (minor) issue I had is that it doesn't work on "some" google docs. With most google docs it works fine but with [this sheet ](https://docs.google.com/spreadsheets/d/1-7JMc6ux0jSblGbQsV0qB1f2mNdVz1XqODMkLqMoShw/htmlview?sle=true#) for example it doesn't. Don't know why, you'll probably know I guess.

No other issue for now.

Hope you can release it soon, thanks again for the work.

**Comment by raburton** [comment]
Thanks for the feedback. Oddly, that google sheet works fine for me, tried with normal right button and with both shift and alt (separately, no mouse button), on Windows, FF 69.0 and it's ok here. So not sure what to say about that.

**Comment by raburton** [comment]
Added in 9102d8e95e722dac617468a711479fb51ca733a9
