### ISSUE TITLE
Slow the scroll rate

### ISSUE THREAD

**Issue by oren64** [raburton/tabscroller#11]
Please add a slider to control the scroll rate. Every small touch of scroll wheel it switched between the tabs some time more than 1.

**Comment by raburton** [comment]
Hi, sorry for the slow reply I was away on staycation.
The code responds to the scroll event, which should be generated just once per mouse scroll click. If you're getting multiple tab switches there must be multiple events coming in. Sounds like a driver or sensitivity issue. Do you have a smooth scroll wheel that fires off a lot of scroll events for a tiny amount of movement? If so, and this is deliberate, it might be possible top put in an option for a minimum number of milliseconds to elapse before accepting another event...

**Comment by oren64** [comment]
My mouse is old, so it might be the problem.
I think there need to have an option to change the number of scroll events per switching tab, it works ok if I move the scroll wheel very slowly and I being careful, but I what it to switch a tab like every 1/8 of a turn of the scroll wheel and not 1/60.

Thanks for your reply.

**Comment by raburton** [comment]
Sorry about the delay, but I have hopefully got a solution for you. I've added a rate limiting option, so you can specify a minimum number of milliseconds before another scroll event is accepted. I've uploaded it to a new branch for testing: https://github.com/raburton/tabscroller/tree/limit Are you able to test this? If you download this branch, then go to firefox addons page and click the gear, choose debug addons and then you can load temporary addon and point it to the folder with the downloaded files in it.

**Comment by oren64** [comment]
I test it with two mouses, and it worked great, I like that the page is not scrolling when the right click is pressed and scroll, compared to current version.
Also, I think you need to set the default interval to ~250ms, in one mouse I like 300ms and in other 500ms.
Otherwise, I didn't find any issues except adding an icon.
This is a big improvement.
Thank you!

**Comment by raburton** [comment]
Glad it's working. Getting the page to not scroll when changing tab was the bit that took a while to figure out. Turns out it was something to do with a change in Firefox a while ago with the event handler. I'm going to leave the default as 0 (off) because I don't think most people want/need this, and so I don't want to change the default behaviour. In 4 years you're the only person to report this problem - so this feature is really just for you! I'll test for a few more days before uploading to the addons site.

**Comment by oren64** [comment]
Thanks!
