### ISSUE TITLE
FVD Speed Dial problem or Blacklist support

### ISSUE THREAD

**Issue by merlin555** [raburton/tabscroller#12]
Hi,

Ingenious plugin !

I still use the "FVD Speed Dial" plugin.
https://addons.mozilla.org/de/firefox/addon/fvd-speed-dial

Unfortunately, when you switch to the "FVD Speed Dial" tab, the tab remains forever.
You then have to select another tab to make it work again.

The link address of the FVD is:
"moz-extension: //918cd55e-361a-4e54-b8c3-cfd82cf30d7e/newtab.html"

Caution ! The link address at the beginning (918cd55e-361a-4e54-b8c3-cfd82cf30d7e) changes if necessary. (user?)

Or you can make a blacklist in the options where you can insert this link address and others as needed?

Thank you !

Greetings ..

  Merlin

**Comment by raburton** [comment]
Yes, the new tab page either captures the mouse events, or tab scroller isn't allowed to run on that page (I think I remember reading somewhere that addons can't interact with each other, but I can't find it now so I might be wrong).
I don't think there is anything I can do about this. I don't know what you mean about having a blacklist?

**Comment by merlin555** [comment]
Hi,

It's a shame, your program is so good.

You could program it so that your TabScroller tool,
simply ignores the title name of the page and always leaves it out. ??

I made a video for you here.
[https://mega.nz/file/F8hBBKRb#qJhkXjRViWLGjBP2w9x-4qH68pxEemgWBwaDC2vy5CU](url)

By blacklist I mean that I can simply enter the address where FVD is in the blacklist.
For me it would be "moz-extension: //918cd55e-361a-4e54-b8c3-cfd82cf30d7e/newtab.html"
That would also solve the problem.
Everything that is in the blacklist is simply ignored and skipped over by TabScroller.

That shouldn't be a problem for you.

Greetings...

**Comment by raburton** [comment]
Ok, so blacklisted pages would be skipped when scrolling? You'd jump to the next tab after it, in whichever direction you're moving? Seems like odd behaviour most people wound't be expecting, but I supposed it'd be an advanced option which people would have to choose to use, so most people wouldn't ever see. I'll have a look...

**Comment by merlin555** [comment]
Thank you for your prompt reply.
That would be very nice of you.

But I think the blacklist is a good idea.

I switched off "Wrap scrolling" in the TabScroller options.
Only if that is important for information.

Yes, with the blacklist or maybe you have an even better idea that FVD,
will skip and omit this tab, no matter where the tab is in Firefox.
Even if it occurs several times!
It would be possible.

And because of the WARP scrolling option, if the FVD tab is at the far left
or at the beginning, the TagScanner notices this and does not know how to go any further.

**Comment by raburton** [comment]
I'm really sorry, I prototyped a blacklist for you but must have got distracted and forgot to post a link to it for you to test! I only realised when adding another requested feature.
If you're still interested you can find it here: [tabscroller-v1.0.9.1.zip](https://github.com/raburton/tabscroller/files/9913412/tabscroller-v1.0.9.1.zip) It'll need to be loaded as a temporary extension from the addons debugging page.

**Comment by merlin555** [comment]
Hi raburton,

Thanks !
It works.
But you can add only one URL link.
Otherwise, if there are several links, nothing will work at all.
Can you do that, you can add multiple URL links ?

And important would be an export function to save all settings as a file.

Greetings..

**Comment by raburton** [comment]
Oops, fixed. 

Replace the current `skipurls = result.skipurls.split('/\r?\n/');`
with `skipurls = result.skipurls.split(/\r?\n/).filter(element => element);`
in background.js (in the ` updateConfig` function) and it should fix it.

I think adding an export for the settings might be overkill, there are only a couple of tick boxes (most of which, most people will use default) and the list of urls can just be copied and pasted.

**Comment by merlin555** [comment]
Great !
Works now.
Please release.

**Comment by raburton** [comment]
It's released. It needs a new permission to be able to access the tabs url, but I've made this an optional permission, only requested if the black list feature is used. As you've had a preview installed, you'll need to go back to the setting and click save again (once you update to the latest release version), this should prompt you to give the extra permission. Or just manually enable to optional permission in the addon list.

**Comment by raburton** [comment]
included in release v1.0.10

**Comment by merlin555** [comment]
Hi raburton,

Thanks very much !
Finally, it works.

Greetings..

  Merlin
