### ISSUE TITLE
Gets stuck on loading tabs, Ignores unloaded tab status

### ISSUE THREAD

**Issue by bottleblue** [raburton/tabscroller#14]
When a website is in the process of loading I'm unable to tab scroll at all until it's finished. So if a site is loading very slow I can't just scroll to another tab. I have to wait or move my mouse and click on a tab. Another addon also has this problem so I'm guessing it's a Firefox issue. I wished somebody could find a workaround.

Also tabs that are unloaded get focused/opened when scrolling. There should be an option to allow it or disallow it and skip past the unloaded tab.

**Comment by raburton** [comment]
I'll have a look, I might be able to find a way to skip these...

**Comment by bottleblue** [comment]
I've been using Gesturefy and it's wheel gesture option focus left/right tab skips unloaded tabs without problems.

**Comment by raburton** [comment]
How are your tabs unloaded? I've got it to skip tabs I have unloaded (but still show on the tab bar) using an extension, but not sure if that's the same as what you need.

Also got it skipping tabs that are still loading (i.e. your slow web site example).

**Comment by bottleblue** [comment]
I'm not sure. When I close and reopen Firefox all tabs from previous session are unloaded except the last one I was on. The extensions I have that are tab related are Unload Tab from Context Menu, Tab Session Manager, FoxyTab, Open Tabs Next to Current, and Tab Mix - Links.  I've tested it with all of them disabled but the issue is still there. 

If it's working for you then it's probably something to do with my extensions or settings. It's fine though I'm not that fussed about it.

**Comment by raburton** [comment]
> If it's working for you then it's probably something to do with my extensions or settings. It's fine though I'm not that fussed about it.

No, I mean I've made changes to get it to do what you want. Please test this new version out (you'll need to go to the options and enable these new features as they are not default behaviour): [tabscroller-v1.0.9.1.zip](https://github.com/raburton/tabscroller/files/9913412/tabscroller-v1.0.9.1.zip)
If you don't know how to load a temporary version of the addon, please see here: https://blog.mozilla.org/addons/2015/12/23/loading-temporary-add-ons/

**Comment by bottleblue** [comment]
Yea it skips unloaded tabs now. But it still doesn't work on websites that haven't partially loaded or loaded enough.  You can try it on a site like 163.com, which loads very slow for me since it's a chinese site and I'm in NA. 

Someone told me it was a limitation of Firefox. They said the addon can't run code if the page isn't loaded

**Comment by raburton** [comment]
With the new skip not fully loaded pages option enabled, it skips right over the 163.com tab for me, right up until it timesout out, then I can scroll to the Firefox error page.

**Comment by bottleblue** [comment]
If I'm not on the tab that's loading (or trying to load) then I can skip it but if I'm on the tab and it's loading very slow or it's a blank white page it won't respond to tab scrolling. That's what I meant by it gets stuck on loading tabs.

**Comment by raburton** [comment]
Yes, you're correct if you're actually on the slow loading page the extension content won't be loaded yet, so you won't be able to scroll away from it. No way around that. I almost always open tabs in the background then scroll to them, and in the cases where I open a link in the current tab I generally want the content now so will wait for it and not try to scroll straight away, so I hadn't tested your scenario.

I though you were looking to skip over these pages while scrolling through tabs (I guess you probably did want that as well), that is possible and now works.

**Comment by bottleblue** [comment]
I usually open tabs in the background too. It was annoying scrolling to a tab that didn't load properly and then I'm unable to scroll out, similar to scrolling to an official mozilla page. But you fixed the scrolling for unloaded tabs so thx a lot for that!

**Comment by raburton** [comment]
now released in v1.0.10
