### ISSUE TITLE
Tabscroller not working anymore

### ISSUE THREAD

**Issue by Conobi** [raburton/tabscroller#16]
Hey, tabscroller doesn't work anymore here.
Here is my device: 
```
Mozilla Firefox 106.0.4 (64 bits) - For Arch Linux
OS: Manjaro Linux x86_64 
Kernel: 6.0.7-lqx1-1-lqx 
DE: GNOME 42.5 (Wayland) 
WM: Mutter
```
It's running on v1.0.10. Can't confirm if its due to v1.0.10, but it seems the case

**Comment by raburton** [comment]
Sorry about that. I'll give it a test on a Linux system as soon as I can get a moment. In the meantime, could you try enabling the optional 'tabs' permission for the add-on, and see if that makes any difference. The new version tries to use the API, but if it's not got permission it happily carries on without. I wonder if it might behave differently on Linux (only thing I can think of, but not sure why it would be).

**Comment by Conobi** [comment]
Already tried! No effect/difference.
The extension console output this btw:
![image](https://user-images.githubusercontent.com/5563277/200135647-09e11c67-7a36-43c5-860b-0c7abdf79f92.png)

**Comment by raburton** [comment]
Hmm, I think I've recreated it. Try adding something to the skip list, like "about:config" and I think it'll work then. I'll quickly sort and test a fix...

**Comment by raburton** [comment]
So it seems it was a bad default value of one of the new configuration options (skip by url option). Once it's set (even if the actual value has been cleared again) it's ok. I've pushed a fix already...

**Comment by Conobi** [comment]
It works back, nice!
Thanks for you work btw bro, your extension is a life-changer, I use it everyday since 5 years and it's probably the most underrated Firefox extension.

**Comment by raburton** [comment]
No problem, glad you've found it useful.

And thank you for your prompt bug report, so I was able to get a fix out quickly.
