### ISSUE TITLE
[Feature Request] Scroll when hovering over tab toolbar

### ISSUE THREAD

**Issue by justinrissler** [raburton/tabscroller#2]
Requesting a feature/option to scroll through tabs when hovering over the tab list (toolbar), no right-clicks involved. :wink: (Here from Quantum that broke a similar addon feature... Also on Linux)

**Comment by raburton** [comment]
Hi. Sorry, but that isn't possible with a WebExtension. There are a limited number of interaction options available with the browser itself (such as adding buttons to the toolbar or adding menu options: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface). It does not allow for capturing events for other browser/user interface components: https://bugzilla.mozilla.org/show_bug.cgi?id=1246706#c16
There is a feature request open against Firefox for this specific functionality: https://bugzilla.mozilla.org/show_bug.cgi?id=1285812

**Comment by justinrissler** [comment]
What a mess. So if I read correctly, the main, or one of the main reasons they're limiting the capabilities of "WebExtensions" is simply so they'll work more universally, or more specifically, with other browsers like Chrome? Seems very limiting.
Where do devs turn to now, to design addons that actually change Firefox's behavior? They have to get their code/feature approved by some guy over at Mozilla, and then if it's approved, it becomes part of everyone's Firefox? I don't understand.

Sorry to be somewhat off-topic and ranty, but I'm guessing it's possible someone might find this when searching for this feature in the new Firefox.

**Comment by raburton** [comment]
The old system was a mess. No permissions model, no security, hooking in to the browser in wierd and wonderful ways that tended to break with each new version of the browser. The new system fixes all these problems. The downside is that addons are more limited in that they can only do what the API allows and if you want a new API or a change to the base product not covered by the API you have to ask the developers for it (as you would with anything else). Firefox was much more hackable before than most applications, but that wasn't necessarily a good thing and it was certainly open to abuse, addons weren't multi process safe and were incompatible version to version. This really held Firefox back, only now this mess has been dropped have they been able to release this vastly improved version which is back on par with modern browsers like Chrome, which had pulled far ahead.
Your rant is fine, but I think I take a different view on the situation and we certainly aren't the only two people with differing views on the new Firefox!

**Comment by ChristianKurz** [comment]
Just as a headsup, here is a workaround to get the old functionality back:
[https://forum.manjaro.org/t/howto-enable-tab-switching-in-firefox-using-mouse-wheel/39954](https://forum.manjaro.org/t/howto-enable-tab-switching-in-firefox-using-mouse-wheel/39954)

**Comment by justinrissler** [comment]
> https://forum.manjaro.org/t/howto-enable-tab-switching-in-firefox-using-mouse-wheel/39954

Thanks for this! +1 works

**Comment by kroseneg** [comment]
There's a new preference in about:config since Firefox 65:
`toolkit.tabbox.switchByScrolling`

https://bugzilla.mozilla.org/show_bug.cgi?id=1512493
