### ISSUE TITLE
Firefox 58 Support

### ISSUE THREAD

**Issue by aaronmendo** [raburton/tabscroller#5]
Hi,

When will Firefox 58 Support be introduced.

Thanks,
Aaron.

**Comment by raburton** [comment]
It already supports v58. In fact it always has - no changes were needed for it to work in v58 or v59, as was just released. However, Linux/OSX support only became possible at v58 (and did require changes to the addon, which were release while v58 was still in beta).

**Comment by jusore** [comment]
Will work on Linux v59?

**Comment by raburton** [comment]
Should work fine on Linux from v58 onwards.
