### ISSUE TITLE
Doesn't Appear to Work on Ubuntu

### ISSUE THREAD

**Issue by eviljoel** [raburton/tabscroller#7]
Nuf' said.

**Comment by raburton** [comment]
Can you tell me what versions of Ubuntu, Firefox and the tabscroller you are using, and which window manager, and I'll set up a VM and have a look.

**Comment by eviljoel** [comment]
Yeah, I guess that was obvious: Ubuntu 18.04 LTS (AMD 64) (default Gnome Shell), Firefox 61.0.1 (64-bit), and TabScroller 1.0.6.

Feel free to ask me to test again or for any other information.

**Comment by eviljoel** [comment]
Sorry, I misunderstood how this works. I thought it worked like the old Tab Wheel Scroll extension, but apparently you hover over the page to scroll the tabs, not the tabs themselves. Actually, it says that in the description which I didn't read closely enough.

Given the name of your app, you might want to make this behavior obvious in the first line of your extension description.

Thanks for the extension.

**Comment by raburton** [comment]
This isn't possible with an extension, but there are ways to do it: https://github.com/raburton/tabscroller/issues/2

**Comment by eviljoel** [comment]
Awesome! Thanks.
