### ISSUE TITLE
Support hidden tabs

### ISSUE THREAD

**Issue by katzelad** [raburton/tabscroller#8]
For interoperability with extensions such as Simple Tab Groups, hidden tabs should not be showed.

**Comment by raburton** [comment]
Please try this, should exclude hidden tabs:
https://www.dropbox.com/s/rr6f3jw0cu070bz/tabscroller-1.0.6.1-fx.xpi?dl=1
Give it a good test and let me know, if it does the job I'll upload it to the add-on site.

**Comment by katzelad** [comment]
Seems good, thanks

**Comment by raburton** [comment]
included in v1.0.7 which is now available form the official addon site

**Comment by katzelad** [comment]
Please take a look at my PR.

**Comment by raburton** [comment]
uploaded in v1.0.7.2
